### DISCUSSION TITLE
refarch missing dynamodb stack?

### DISCUSSION THREAD

**Discussion by rauthur** [cloudposse/community#13] [Essential Support] [answered]
Should there be a dynamodb stack in the tgz? I'm not seeing one and that prevents bootstrapping the tfstate backend.

e.g., no matches found for the import 'catalog/dynamodb/defaults'

**Comment by milldr** [comment]
There should be a default dynamodb stack included under `stacks/catalog/dynamodb/defaults.yaml`. If it's not there, this is what it should be:

```yaml
components:
  terraform:
    dynamodb/defaults:
      metadata:
        type: abstract
        component: dynamodb
      vars:
        enabled: true
        hash_key: HashKey
        range_key: RangeKey
        billing_mode: PAY_PER_REQUEST
        autoscaler_enabled: false
        encryption_enabled: true
        point_in_time_recovery_enabled: true
        streams_enabled: false
        ttl_enabled: false
```

**Reply by milldr** [reply, marked as answer]
To clarify, there are 2 different implementations with DynamoDB. We have a `dynamodb` component that is a basic implementation of DynamoDB that we use for the Atmos Terraform GitHub Actions, referred to as `gitops`, as well as other basic use-cases. 

But we also have a `tfstate-backend` component that has a separate implementation of DynamoDB specifically tied into Terraform State. That second case is included in the `tfstate-backend` component directly and does not depend on `catalog/dynamodb/defaults`

**Reply by rauthur** [reply]
Thanks, that makes sense. It looks like we have a gitops.yaml but are missing the basic dynamodb (your first item) leading to the error as the gitops.yaml references the non-existent dynamodb defaults. So, even though I'm running an unrelated command to provision the tfstate backend I hit an error as the referenced dynamodb stack cannot be found.

Adding the simple yaml version you included above seems to address the issue.

For clarity here is the full error:

```
no matches found for the import 'catalog/dynamodb/defaults' in the file 'catalog/gitops.yaml'
Error: failed to find a match for the import '/localhost/Projects/infrastructure/stacks/catalog/dynamodb/defaults.yaml' ('/localhost/Projects/infrastructure/stacks/catalog/dynamodb' + 'defaults.yaml')
```

**Reply by milldr** [reply]
ah I see. Yes all stacks configurations needs to be valid. And default catalog entry is used to build the configuration for the gitops use case. 

As a tip, you can use [Atmos to validate stacks](https://atmos.tools/cli/commands/validate/stacks) and catch any missed imports a little faster:

```bash
atmos validate stacks
```

**Reply by osterman** [reply]
@rauthur I think there was a bug in what we delivered to you. @dudymas is working on the fix and will post an update shortly.

**Reply by dudymas** [reply]
So basically you'll want to create a file `components/terraform/dynamodb/component.yaml` with these contents:
```
apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/dynamodb?ref={{ .Version }}
    version: 1.416.0
    included_paths:
      - "**/**"
    excluded_paths: []
```

Then run `atmos vendor pull --component dynamodb` to update the code. This along with the default config that @milldr mentioned above should fix things up and also help you familiarize with how to add/update components.
