### DISCUSSION TITLE
ECR Pull Through cache

### DISCUSSION THREAD

**Discussion by mtb-xt** [cloudposse/community#27] [Essential Support] [answered]
It would be awesome, if we could configure the [pull through cache rules](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-creating-rule.html) with one of CloudPosse modules.

**Comment by GabisCampana** [comment]
@osterman

**Comment by milldr** [comment, marked as answer]
We have pull through cache rules included with our `ecr` component!
https://github.com/cloudposse-terraform-components/aws-ecr

To add pull through caching with `ecr`, add this to your stack configuration
```yaml
components:
  terraform:
    ecr:
      vars:
        enabled: true
...
        pull_through_cache_rules:
          dockerhub:
            registry: "registry-1.docker.io"
            secret: "ecr-pullthroughcache/dockerhub"
```
