### DISCUSSION TITLE
Using the dns-delegated component

### DISCUSSION THREAD

**Discussion by jessegonzalez** [cloudposse/community#29] [Free Tier Support] [answered]
NOTE: This was originally posted in sweetops.slack.com but was asked to post here and has been slightly modified from the original for additional context and clarity.

This is a followup to [discussion #28](https://github.com/orgs/cloudposse/discussions/28).

The module interface for `dns-delegated` accepts a map as [zone_config](https://github.com/cloudposse-terraform-components/aws-dns-delegated/blob/main/src/variables.tf#L6-L12) to define delegated subdomains. If I use this component as follows:

```
components:
  terraform:
    dns-delegated:
      metadata:
        type: real
      vars:
        zone_config:
          - subdomain: stg
            zone_name: example.com
          - subdomain: stg
            zone_name: example.internal
        request_acm_certificate: true
        dns_private_zone_enabled: false
```

I have the following observations:

**Observation 1:**

The dns-delgated interface does not allow for creation of both private and public zones with the avialable zone_config interface.

**Observation 2:**

The module does not appear to properly handle the above zone_config input using the `zipmap` function in locals:

```
zone_map = zipmap(var.zone_config[*].subdomain, var.zone_config[*].zone_name)

## this becomes
## zipmap (["stg", "stg"], ["example.com", "example.internal"])
##
## and ultimately
## {
##   "stg" = "example.internal"  
## }
```

**Observation 3:**

There are a handful of [references](https://github.com/search?q=org%3Acloudposse-terraform-components+dns-delegated+path%3Aremote-state.tf&type=code) in cloudposse-terraform-components usinga hardcoded `remote_state` references to `dns-delegated`.

But as you pointed out in the [post](https://sweetops.slack.com/archives/C031919U8A0/p1736938834199639) by [@Pablo Paez](https://sweetops.slack.com/team/U087UQVF7FX), you are working to eliminate that this year.

**Questions:**

* Since we do need both private and public hosted zones, is the recommended approach here to use the multiple component instances pattern? Something like following:

```
components:
  terraform:
    dns-delegated/private:
      metadata:
        type: real
        component: dns-delgated 

      vars:
        zone_config:
          - subdomain: stg
            zone_name: example.internal
        request_acm_certificate: true
        dns_private_zone_enabled: true

    dns-delegated/public:
      metadata:
        type: real
        component: dns-delgated 

      vars:
        zone_config:
          - subdomain: stg
            zone_name: example.com
        request_acm_certificate: true
        dns_private_zone_enabled: false
```
