### DISCUSSION TITLE
Issue with `github-action-atmos-affected-trigger-spacelift` Not Triggering Affected Stacks

### DISCUSSION THREAD

**Discussion by milldr** [cloudposse/community#32] [Essential Support] [answered]
## Context

We’ve encountered an issue with the `cloudposse/github-action-atmos-affected-trigger-spacelift` GitHub Action after a recent update (see [PR #48](https://github.com/cloudposse/github-action-atmos-affected-trigger-spacelift/pull/48)). The action is now failing to trigger the affected Spacelift stacks when a PR is merged.

### Initial setup

Our workflow was configured as follows:

```yaml
name: "Deploy Affected Spacelift Stacks"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run:
    if: github.event.pull_request.merged == true
    runs-on:
      group: vnext
    steps:
      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.sha }}~1
          install-jq: true
          jq-version: 1.7
          atmos-version: 1.153.0
```

The error we encountered indicates that the action is not detecting any affected stacks:

![image](https://github.com/user-attachments/assets/2a35dfbb-3228-49ef-ad56-d9558b7e092b)

### Summary of Discussion

https://sweetops.slack.com/archives/C0313BVSVQD/p1738773568526219

#### Trigger vs. Head Ref:
1. Should we modify the workflow trigger (from pull_request to push) or simply remove the explicit head-ref parameter for PR events?
1. What are the potential trade-offs of each approach?

#### Impact of Atmos Changes:
1. What specific changes in Atmos versions (e.g., around 1.157.0 or later) might be affecting the action’s behavior?
1. Should we consider enforcing the use of --clone-target-ref in the action for consistency?

#### Action Versioning:
1. Even though we’re using @v2, it should include the fixes from v2.1.0. Do we need to update the action version or pin to v2.0.1 as an interim solution?

#### Long-Term Resolution:
1. How can we adjust our workflows to accommodate both the new Atmos behavior and the commit strategies (squash vs. merge) to reliably detect affected stacks?

**Comment by milldr** [comment]
### Atmos Version Behavior

In older Atmos versions the command `atmos describe affected` would clone the target branch from the remote, whereas newer versions perform a local checkout. The flag `--clone-target-ref=true` can be used to force cloning, which might be necessary if the target branch isn’t available locally.

**Comment by milldr** [comment]
### Workaround with `get-pr`

Updating the workflow to run on a push to main with a checkout; however, this resulted in both the `base-ref` and `head-ref` having the same value, and no affected stacks were detected. He then implemented a workaround using [cloudposse-github-actions/get-pr@v2](https://github.com/cloudposse/github-actions-get-pr), which retrieves the correct base and head commit SHAs. Here’s the snippet used:

```yaml
jobs:
  pr:
    name: PR Context
    steps:
      - uses: cloudposse-github-actions/get-pr@v2
        id: pr
        with:
          github-token: ${{ secrets.GH_PAT }}
    outputs:
      base: ${{ fromJSON(steps.pr.outputs.json).base.sha }}
      head: ${{ fromJSON(steps.pr.outputs.json).head.sha }}

  run:
    if: github.event.pull_request.merged == true
    needs:
      - pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          deploy: true
          github-token: ${{ secrets.GH_PAT }}
          base-ref: ${{ needs.pr.outputs.base }}
          head-ref: ${{ needs.pr.outputs.head }}
          install-jq: true
          jq-version: 1.7
          atmos-version: 1.153.0
```

**Comment by milldr** [comment]
### Head Ref Issue with Squash Commits

Our configuration uses squash commits. Using `head-ref: ${{ github.sha }}~1` in this scenario seems to produce an incorrect comparison (i.e., comparing the current SHA to the previous SHA from the PR rather than the intended base branch). This might be why the diff isn’t detected properly.

**Comment by milldr** [comment]
## Solution

The problem is a conflict between where the workflow is called and what we're setting as `head-ref`. We can do this a few different ways, but what we have above is creating the conflict.

What we have above is triggered on `pull_request` and sets the head ref to `${{ github.sha }}~1`. This means that we're comparing the current sha (base sha) against latest sha minus 1 for the pull request. That's not want we want. Instead we could do 1 of 2 things:

Change the trigger to on pushes to `main`. That would mean when we set the head ref to `${{ github.sha }}~1` it would compare the current sha for `main` against 1 previous sha on `main`, which includes everything from the PR. This would work, but instead we prefer the next option

Alternatively, we should keep the trigger for on `pull_request` but delete the line with `head_ref`. If not provided, the action will get the sha of the default branch. That would mean compare the default branch (`main`) sha to the PR sha -- which is what we want.

You can also use `get-pr` to solve the problem. The important piece is that the head and base refs are correct

**Reply by milldr** [reply]
This is Spacelift, so we have to run on pull request closed. That is because we trigger Spacelift using a comment on the PR. So with that in mind, try this out:

```yaml
name: "Deploy Affected Spacelift Stacks"

on:
  pull_request: # required to trigger on PRs since Spacelift is triggered by comments on a PR
    types: [closed]
    branches:
      - main

jobs:
  run:
    if: github.event.pull_request.merged == true
    runs-on: ["self-hosted", "default"]
    steps:
      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.event.pull_request.head.sha }} # We need to specify the head branch SHA -- the SHA of the PR target / main
          skip-atmos-functions: "true" # optional if using atmos latest version, > 1.158.0
```

(update: removed `base-ref`)

**Reply by RoseSecurity** [reply]
@milldr I updated our workflow to use this solution and was greeted with:

```console
Warning: Unexpected input(s) 'base-ref', valid inputs are ['atmos-config-path', 'atmos-version', 'default-branch', 'deploy', 'github-token', 'head-ref', 'install-atmos', 'install-jq', 'install-spacectl', 'install-terraform', 'jq-force', 'jq-version', 'spacectl-version', 'spacelift-api-key-id', 'spacelift-api-key-secret', 'spacelift-endpoint', 'terraform-version', 'trigger-method', 'skip-atmos-functions']
```

Would the advisable solution be to adjust the trigger to be on pushes to main with the `head-ref` set to `${{ github.sha }}~1`

**Reply by milldr** [reply]
Yes that's my mistake. base-ref is not necessary. It's discovered in the nested action, cloudposse/github-action-atmos-affected-stacks

**Reply by milldr** [reply]
> Would the advisable solution be to adjust the trigger to be on pushes to main with the head-ref set to ${{ github.sha }}~1

No because this is a Spacelift trigger. In order to trigger spacelift, we add a comment to the PR -- which Spacelift monitors. Therefore it has to be triggered on the PR event.

Does this below solve your issue? (1) trigger on PR, (2) set head-ref, (3) remove base-ref and skip-atmos-functions

```yaml
name: "Deploy Affected Spacelift Stacks"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run:
    if: github.event.pull_request.merged == true
    runs-on: ["self-hosted", "default"]
    steps:
      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.event.pull_request.head.sha }}
```

**Reply by milldr** [reply, marked as answer]
We had a misunderstanding with the git references and further discussed this in Slack. Following up here for any future reference:

The issue is that by the time the PR has merged, the sha of the main branch (base-ref) has been updated, so we're comparing the wrong diff. Instead, we need to get the previous sha of the main branch, but since the workflow is running on the PR we need to first fetch the history of the base ref.

Here's the solution:

```yaml
name: "Deploy Affected Spacelift Stacks"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run:
    if: github.event.pull_request.merged == true
    runs-on: ["self-hosted", "default"]
    steps:
      - name: Checkout repository with extra history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # We want to use 1 previous commit from the base branch SHA
      # This is because by the time this workflow runs, the PR branch has already been merged.
      # It's critical to use the base branch SHA to get the correct changes, not the previous commit from the PR branch.
      - name: Determine previous commit on base branch
        id: get_parent
        shell: bash
        run: |
          # For squash merges, github.event.pull_request.base.sha represents the state of the base branch
          # when the PR was created (or last updated). This may be stale compared to the actual commit
          # on the main branch at the time of the merge. Using 'HEAD~1' after the merge ensures we get
          # the commit that was the tip of main immediately before the squash merge commit was added.
          echo "Merge commit: $(git rev-parse HEAD)"
          PARENT=$(git rev-parse HEAD~1)
          echo "Parent (base) commit: $PARENT"
          echo "parent_commit=$PARENT" >> "$GITHUB_OUTPUT"

      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-atmos-functions: "true"
          head-ref: ${{ steps.get_parent.outputs.parent_commit }}
```
