### DISCUSSION TITLE
Atmos fails to validate against schema when using hooks

### DISCUSSION THREAD

**Discussion by mtb-xt** [cloudposse/community#35] [Essential Support] [answered]
Hi team,

Trying to add storage of outputs in ssm, as per this document - https://atmos.tools/core-concepts/stacks/hooks/#supported-lifecycle-events

After adding hooks configuration to a component in the catalog, or directly in the stack, I'm getting validation errors:

```
 √ . [nsp-identity] (HOST) platform ⨠ atmos validate stacks
ERRO Atmos manifest JSON Schema validation error in the file 'orgs/nsp/core/auto/ap-southeast-2/network.yaml':
{
  "valid": false,
  "errors": [
    {
      "keywordLocation": "",
      "absoluteKeywordLocation": "file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#",
      "instanceLocation": "",
      "error": "doesn't validate with file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#"
    },
    {
      "keywordLocation": "/properties/components/$ref",
      "absoluteKeywordLocation": "file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#/properties/components/$ref",
      "instanceLocation": "/components",
      "error": "doesn't validate with '/definitions/components'"
    },
    {
      "keywordLocation": "/properties/components/$ref/properties/terraform/$ref",
      "absoluteKeywordLocation": "file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#/definitions/components/properties/terraform/$ref",
      "instanceLocation": "/components/terraform",
      "error": "doesn't validate with '/definitions/terraform_components'"
    },
    {
      "keywordLocation": "/properties/components/$ref/properties/terraform/$ref/patternProperties/%5E%5B~1a-zA-Z0-9-_%7B%7D.%20%5D+$/$ref",
      "absoluteKeywordLocation": "file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#/definitions/terraform_components/patternProperties/%5E%5B~1a-zA-Z0-9-_%7B%7D.%20%5D+$/$ref",
      "instanceLocation": "/components/terraform/vpc",
      "error": "doesn't validate with '/definitions/terraform_component_manifest'"
    },
    {
      "keywordLocation": "/properties/components/$ref/properties/terraform/$ref/patternProperties/%5E%5B~1a-zA-Z0-9-_%7B%7D.%20%5D+$/$ref/additionalProperties",
      "absoluteKeywordLocation": "file:///localhost/gh/platform/stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json#/definitions/terraform_component_manifest/additionalProperties",
      "instanceLocation": "/components/terraform/vpc",
      "error": "additionalProperties 'hooks' not allowed"
    }
  ]
}
```

This is what I'm trying to do:

```
components:
  terraform:

    vpc:
      hooks:
        store-outputs:
          events:
            - after-terraform-apply
          command: store
          name: prod/ssm
          outputs:
            vpc_id: .id    
      metadata:
        component: vpc
        inherits:
          - vpc/defaults
```
