### DISCUSSION TITLE
Receiving error: component vendoring config file does not exist in the '/workspace/components/terraform/tgw' folder

### DISCUSSION THREAD

**Discussion by ron-johnson** [cloudposse/community#39] [Essential Support] [answered]
I am going through the cold start in the network configuration step and getting the following error:

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/6c0dd450-9d79-4be1-afc3-c53d1e953642" />

Our workflow is as follows:

```yaml
  vendor:
    description: Vendor component dependencies for the network layer.
    steps:
      - command: vendor pull --component tgw
      - command: vendor pull --component acm
      - command: vendor pull --component bastion
      - command: vendor pull --component dns-delegated
      - command: vendor pull --component dns-primary
      - command: vendor pull --component ec2-client-vpn
      - command: vendor pull --component vpc
``` 

Any suggestions?
