### DISCUSSION TITLE
Leveraging eks-blueprints/kubernetes-addons without eks-blueprints eks module

### DISCUSSION THREAD

**Discussion by nitrocode** [cloudposse/community#4] [Free Tier Support] [answered]
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/0529549fa2f4b07f65c199c2573b81b2e979aa56/examples/eks-cluster-with-new-vpc/main.tf#L[…]1

This example shows soooo many kubernetes addons to use with simple switches and all we’d need to do is feed in the eks cluster id 

I know we spoke about eks blueprints before but I don’t know if we spoke specifically of the kubenetes-addons submodule in conjunction with our eks module

**Comment by osterman** [comment]
It sounds interesting. I just wish there was some way we could do a catalog-based approach without needing to define a hundred components that wrap their modules.

**Reply by nitrocode** [reply]
Couldn't we just create a component that uses the kubernetes addons submodule that they provide? Then all we would have to do is expose each of those inputs to variables.tf and then it would be available through the catalog.

```yaml
components:
  terraform:
    eks/cluster:
      vars:
        enabled: true
        name: eks

    eks/cluster-addons:
      metadata:
        component: eks/cluster-addons
      vars:
        enabled: true
        eks_component_name: eks/cluster

        enable_aws_load_balancer_controller: true
        enable_metrics_server: true
        enable_aws_cloudwatch_metrics: true
        enable_kubecost: true
        enable_gatekeeper: true
        # ...etc
```
