### DISCUSSION TITLE
Receiving error "Missing the key LockID in the item" from github-action-atmos-terraform-plan

### DISCUSSION THREAD

**Discussion by Maciej-Gadomski** [cloudposse/community#47] [Free Tier Support] [answered]
Hello, during execution of github-action-atmos-terraform-plan, I receive "Missing the key LockID in the item" error message which comes from github-action-terraform-plan-storage. Plan file was successfully stored in s3 and then dynamo error appear. Any ideas?

```yaml
name: Plan Atmos Component
uses: cloudposse/github-action-atmos-terraform-plan@v4
with:
    component: ${{ matrix.component }}
    stack: ${{ matrix.stack }}
    atmos-config-path: .
    atmos-version: 1.165.2
```

**Comment by milldr** [comment]
This error is likely an indicator that the DynamoDB table is misconfigured. Do you have `integrations.github.gitops` configured in your atmos config?

See these docs for reference: https://atmos.tools/integrations/github-actions/#atmos-configuration

**Reply by Maciej-Gadomski** [reply]
yes i have it configured.

**Reply by milldr** [reply]
can you share what you have please? And can you also share your DynamoDB table configuration itself?

**Reply by Maciej-Gadomski** [reply]
```yaml
integrations:
  github:
    gitops:
      terraform-version: 1.8.5
      infracost-enabled: false
      artifact-storage:
        region: eu-central-1
        bucket: {bucket_name}
        table: {table_name}
        role: {role_arn}
        metadata-repository-type: dynamo
        planRepositoryType: s3
      role:
        plan: {role_arn}
        apply: {role_arn}
      matrix:
        sort-by: .stack_slug
        group-by: .stack_slug | split("-") | [.[0], .[2]] | join("-")
```
![Screenshot 2025-03-17 at 09 25 46](https://github.com/user-attachments/assets/8d6d1f9a-a645-4d48-8108-69b55b4a5be4)
