### DISCUSSION TITLE
Split up yaml and terraform into service repos

### DISCUSSION THREAD

**Discussion by nitrocode** [cloudposse/community#49] [Free Tier Support] [answered]
Is there a good doc on how to split up terraform from a mono repo to both a mono repo and service repos so it may be possible to collocate infra and its service code ?

E.g. aws account map and account and root components live in mono repo, core shared components like s3-bucket and others are in mono repo, but service repos can contain yaml stacks and even custom non shared terraform components

**Comment by osterman** [comment]
@milldr helped someone else with this recently.

**Reply by milldr** [reply, marked as answer]
Yes we helped a customer with this recently, but we don't have official docs on it yet. Here's a high level summary, and we can add a task to convert this into an official doc page.

## Poly-Repo Strategy with `account-map`

### Problem

You want many repositories to deploy infrastructure as code with Terraform and Atmos. However, the standard `providers.tf` configuration with Cloud Posse components requires `account-map` to dynamically select Terraform roles and target accounts. 

### Solution

#### 1 - Use the `infrastructure` Repo for core services

1. Use the primary `infrastructure` repository to deploy all accounts, Terraform state, and core services
2. Deploy `account-map` here
3. _Download_ the `account-map` Terraform output to use later
4. Optional, highly recommended: Use a custom atmos command to download the account-map output as an artifact

```yaml
# atmos.yaml
...
commands:
  - name: download-account-map
    description: This command downloads the Terraform output for account-map.
    env:
      - key: AWS_PROFILE
        value: cptest-core-gbl-root-admin # change this to a role you can assume with access to account-map
    steps:
      # initialize terraform and selects workspace
      - "atmos terraform workspace account-map core-gbl-root -s core-gbl-root"
      # download the terraform output for account-map. limit atmos to only the JSON output
      - "atmos terraform output account-map -s core-gbl-root --logs-level Off --redirect-stderr=/dev/null --skip-init -- -json | jq 'map_values(.value)' | yq -P -oy > components/terraform/account-map/account-map-output.{{ now | date \"2006-01-02\" }}.yaml"
```

You will need to update this artifact each time account-map changes. This is fairly infrequent, and there are potential solutions for optimization yet to be considered.

#### 2 - Mock `account-map` in each poly-repos

In each of the poly-repos, we need to configure account-map to use a static backend. We want remote-state to read a static YAML configuration when referring to account-map, rather than reading the terraform backend. 

1. Download the `account-map` component (vendoring recommended). We do not need to apply this component, but we do need the submodules included with the component for the common `providers.tf` configuration in all other components
2. Create a component instance for `account-map` -- typically with the stack catalog `stacks/catalog/account-map.yaml`
3. Set `remote_state_backend_type: static`
4. Paste the `account-map` YAML output under `remote_state_backend.static`. I'd recommend using imports to manage the output artifact separately or other ways to make it easier to understand and update.

Done! Now when remote-state refers to the `account-map` component, it will instead check the static remote state backend rather than S3

```yaml
components:
  terraform:
    account-map:
      remote_state_backend_type: static
      remote_state_backend:
        static:
          PASTE OR INCLUDE YAML HERE
          (make sure to set indentation)
```
