### DISCUSSION TITLE
Create and configure subcommands using YAML

### DISCUSSION THREAD

**Discussion by nitrocode** [cloudposse/community#5] [Free Tier Support] [answered]
## Problem:
- I want to modify `terraform init` to add a new flag `-upgrade`. I can do it by contributing a new atmos env var, atmos flag, and golang code, and tests.
- I want to integrate opa before a terraform apply -auto-approve
- I want to integrate other hooks like checkov and tfsec

Or I can do it in workflows which are a good escape hatch https://github.com/cloudposse/atmos#workflows

Or I can use the deep merging from atmos to create my tfvars, the workspace name it generates, and the terraform backend it generates in json and run raw terraform from outside of atmos using choria-io appbuilder. 😄 

Ref:
* [choria-io AppBuilder](https://github.com/choria-io/appbuilder/releases) - [docs](https://choria-io.github.io/appbuilder/quick-start/) - recent updates!
* [ahoy](https://github.com/ahoy-cli/ahoy) - Last release is 2017 and does not support arguments well

Here's an example using choria-io appbuilder and it has a pretty decent interface

### On mac

Install

```sh
brew install atmos yq
brew tap choria-io/tap
brew install choria-io/tap/appbuilder
```

Setup

```sh
mkdir -p ~/Library/Application\ Support/appbuilder/
ln -s $(which appbuilder) /usr/local/bin/atmos-sub
vim ~/Library/Application\ Support/appbuilder/atmos-sub-app.yaml
```

See configuration below

### On geodesic

Install

```sh
apt update && apt install -y atmos yq
wget https://github.com/choria-io/appbuilder/releases/download/v0.0.9/appbuilder-0.0.9-amd64.deb
dpkg -i appbuilder-0.0.9-amd64.deb
rm appbuilder-0.0.9-amd64.deb
```

Setup

```sh
mkdir -p /etc/appbuilder
ln -s $(which appbuilder) /usr/local/bin/atmos-sub
vim /etc/appbuilder/atmos-sub-app.yaml
```

See configuration below

### Configuration

```yaml
name: atmos-sub
description: atmos
author: https://github.com/choria-io/appbuilder
type: parent

commands:
  - name: terraform
    description: terraform subcommands
    type: parent
    commands:
    - name: plan
      description: plan
      arguments:
        - name: component
          description: Name of the component
          required: true
      flags:
        - name: stack
          description: Name of the stack
          required: true
          short: s
      type: exec
      script: |
        set -x
        ATMOS_STACK={{ .Flags.stack | escape }}
        ATMOS_COMPONENT={{ .Arguments.component | escape }}
        ATMOS_BASE_COMPONENT=$(atmos describe component $ATMOS_COMPONENT --stack=$ATMOS_STACK | yq .metadata.component)
        # logic to get the correct terraform workspace
        ATMOS_WORKSPACE=$(atmos describe component $ATMOS_COMPONENT --stack $ATMOS_STACK | yq .workspace)
        # TODO: make the `rm -f` command safer by replacing it with a `find` and `-delete` command
        # The following uses &&s so the command will not continue if a former command fails
        atmos terraform generate backend $ATMOS_COMPONENT --stack $ATMOS_STACK \
        && atmos terraform generate varfile $ATMOS_COMPONENT --stack $ATMOS_STACK \
        && rm -f components/terraform/$ATMOS_BASE_COMPONENT/.terraform.lock.hcl \
        && terraform -chdir=components/terraform/$ATMOS_BASE_COMPONENT \
          init -reconfigure -upgrade \
        && terraform -chdir=components/terraform/$ATMOS_BASE_COMPONENT \
          workspace list \
        && terraform -chdir=components/terraform/$ATMOS_BASE_COMPONENT \
          workspace select $ATMOS_WORKSPACE || terraform -chdir=components/terraform/$ATMOS_BASE_COMPONENT workspace new $ATMOS_WORKSPACE \
        && terraform -chdir=components/terraform/$ATMOS_BASE_COMPONENT \
          plan -out=$ATMOS_WORKSPACE.planfile -var-file=$ATMOS_WORKSPACE.terraform.tfvars.json
```

This command

```sh
atmos-sub terraform plan aws-backup-common --stack mgmt-uw2-sandbox
```

Would run the following

```sh
atmos terraform generate backend aws-backup-common --stack mgmt-uw2-sandbox
terraform -chdir=components/terraform/aws-backup init -reconfigure -upgrade
terraform -chdir=components/terraform/aws-backup workspace list
terraform -chdir=components/terraform/aws-backup workspace select mgmt-uw2-sandbox-aws-backup-common || terraform -chdir=components/terraform/aws-backup workspace new mgmt-uw2-sandbox-aws-backup-common
atmos terraform generate backend aws-backup-common --stack mgmt-uw2-sandbox
atmos terraform generate varfile aws-backup-common --stack mgmt-uw2-sandbox
terraform -chdir=components/terraform/aws-backup plan -out=mgmt-uw2-sandbox-aws-backup-common.planfile -var-file=mgmt-uw2-sandbox-aws-backup-common.terraform.tfvars.json
```

NOTE:
- If working outside of geodesic, then `ATMOS_BASE_PATH` and the `atmos.yaml` will have to be set in order to use the custom provider in the `remote-state.tf`
- One can optionally prefix the command with `BUILDER_DRY_RUN=true` in order to see a dump of the commands that would be run and it would resolve the flags passed in.
