### DISCUSSION TITLE
SSO, Identity Center and Okta

### DISCUSSION THREAD

**Discussion by petabook** [cloudposse/community#65] [Essential Support] [answered]
I saw that there's a new aws-identity-center component. Could you help me understand how to use it? I'd like to set up a single Identity Center for the entire organization, integrated with Okta.

**Comment by milldr** [comment, marked as answer]
the `aws-identity-center` component is identical to the `aws-sso` component you already have. When we migrated from the monorepo library for components, we renamed it to `aws-identity-center` to match AWS. 

Your `aws-sso` component will likely already refer to the new upstream source. For example, you should have this `component.yaml` in `components/terraform/aws-sso`

```yaml
# 'aws-sso' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c aws-sso' or 'atmos vendor pull --component aws-sso'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    # 'uri' supports all protocols (local files, Git, Mercurial, HTTP, HTTPS, Amazon S3, Google GCP),
    # and all URL and archive formats as described in https://github.com/hashicorp/go-getter
    # In 'uri', Golang templates are supported  https://pkg.go.dev/text/template
    # If 'version' is provided, '{{ .Version }}' will be replaced with the 'version' value before pulling the files from 'uri'
    uri: github.com/cloudposse-terraform-components/aws-identity-center.git//src?ref={{ .Version }}
    version: v1.532.0
    # Only include the files that match the 'included_paths' patterns
    # If 'included_paths' is not specified, all files will be matched except those that match the patterns from 'excluded_paths'
    # 'included_paths' support POSIX-style Globs for file names/paths (double-star `**` is supported)
    # https://en.wikipedia.org/wiki/Glob_(programming)
    # https://github.com/bmatcuk/doublestar#patterns
    included_paths:
      - "**/**"
    # Exclude the files that match any of the 'excluded_paths' patterns
    # Note that we are excluding 'context.tf' since a newer version of it will be downloaded using 'mixins'
    # 'excluded_paths' support POSIX-style Globs for file names/paths (double-star `**` is supported)
    excluded_paths: []
```
