### DISCUSSION TITLE
GitHub Actions Drift Detection Failing with Missing runs-on Component Error

### DISCUSSION THREAD

**Discussion by dukarc** [cloudposse/community#69] [Free Tier Support] [answered]
I'm experiencing drift detection failures in our GitHub Actions pipeline for TGW spoke configurations across multiple environments. The main error occurs with the `tgw/spoke/runs-on` component.

## Error Message

Error: Could not find the component 'runs-on' in the stack 'core-usw2-network'.
Check that all the context variables are correctly defined in the stack manifests.
Are the component and stack names correct? Did you forget an import?

<img width="891" alt="image" src="https://github.com/user-attachments/assets/2d21bc9b-0a9d-4755-8b34-115a2ecf982b" />

## Component Setup

In our catalog we have:

# stacks/catalog/tgw/spoke.yaml
```
components:
    tgw/spoke/runs-on:
      metadata:
        component: tgw/spoke
        inherits:
          - tgw/spoke-defaults
      vars:
        own_vpc_component_name: runs-on
        attributes:
          - "runs-on"
        connections:
          - account:
              tenant: core
              stage: network
          - account:
              tenant: core
              stage: auto
            vpc_component_names:
              - vpc
              - runs-on
          - account:
              tenant: plat
              stage: sandbox
          - account:
              tenant: plat
              stage: dev
          - account:
              tenant: plat
              stage: staging
          - account:
              tenant: plat
              stage: prod
```

## Problem

The issue appears to be that our drift detection GitHub Action is trying to validate the `tgw/spoke/runs-on` component for accounts where we don't have the `runs-on` component deployed. The action uses this selection filter:

select-filter: '.settings.github.actions_enabled and .metadata.type != "abstract"'

The `runs-on` component (self-hosted GitHub Actions runners) exists only in the `auto` account, but the drift detection is checking it in all accounts referenced in the catalog configuration.

Has anyone encountered similar issues with the drift detection workflow attempting to validate components that don't exist in certain environments? What's the best approach to fix this?

**Comment by milldr** [comment]
Here you have `runs-on` specified in the catalog.
```yaml
components:
    tgw/spoke/runs-on:
      metadata:
        component: tgw/spoke
        inherits:
          - tgw/spoke-defaults
      vars:
...
        connections:
...
          - account:
              tenant: core
              stage: auto
            vpc_component_names:
              - vpc
              - runs-on # <--------- HERE
```

That means that every time you import `catalog/tgw/spoke`, you will use that configuration. Instead, I would keep the catalog for tgw/spoke generic or the default value for all accounts and only add in `runs-on` in the stack that needs it. (ie move `tgw/spoke/runs-on` to auto and leave default `tgw/spoke` in the catalog)

**Comment by dukarc** [comment, marked as answer]
Met with you guys today ...  The fix was to move the following component from the central component to be defined only in the auto stack

FROM 
catalog/tgw/spoke

TO
stacks/orgs/vbpt/core/auto/us-west-2/network.yaml

```
    tgw/spoke/runs-on:
      metadata:
        component: tgw/spoke
        inherits:
          - tgw/spoke-defaults
      vars:
        own_vpc_component_name: runs-on
        attributes:
          - "runs-on"
        connections:
          - account:
              tenant: core
              stage: network
          - account:
              tenant: core
              stage: auto
            vpc_component_names:
              - vpc
              - runs-on
          - account:
              tenant: plat
              stage: sandbox
          - account:
              tenant: plat
              stage: dev
          - account:
              tenant: plat
              stage: staging
          - account:
              tenant: plat
              stage: prod
```
