### DISCUSSION TITLE
Eks Argo Refarch Setup Question - Post Deploy

### DISCUSSION THREAD

**Discussion by dukarc** [cloudposse/community#72] [Essential Support] [answered]
Hi Folks,

We were able to deploy (`atmos workflow deploy/argocd -f argocd`) and conform our ArgoCD environments are working in dev, staging, and prod.

Following next steps on refarch .. we are confused what to do next
https://docs.cloudposse.com/layers/software-delivery/eks-argocd/setup/#next-steps

We do not see a template github workflow in the starter i.e. `acme/infra-acme/.github/environments`

**Comment by milldr** [comment, marked as answer]
It looks like that's missing from the template. Here's what you'll need to add:
```yaml
# .github/workflows/environments/action.yaml <-- this file path will need to match whatever file path you specify in your reusable workflows
name: "Environments - ArgoCD"
description: "Get information about the environment"
inputs:
  environment:
    description: "Environment name"
    required: true
  application:
    description: "The application name"
    required: false
  namespace:
    description: "Namespace name"
    required: true
outputs:
  name:
    description: "Environment name"
    value: ${{ inputs.environment }}
  region:
    description: "AWS Region"
    value: us-east-1 # cloudposse/github-action-kubernetes-environment does not have a 'region' output. <---- Set this to your default region!
  role:
    description: "IAM Role"
    value: ${{ steps.result.outputs.role }}
  cluster:
    description: "Cluster"
    value: ${{ steps.result.outputs.cluster }}
  namespace:
    description: "Namespace"
    value: ${{ steps.result.outputs.namespace }}
  ssm-path:
    description: "SSM Path"
    value: ${{ steps.result.outputs.ssm-path }}
runs:
  using: "composite"
  steps:
    - uses: cloudposse/github-action-kubernetes-environment@v0.4.1
      id: result
      with:
        environment: ${{ inputs.environment }}
        namespace: ${{ inputs.namespace }}
        application: ${{ inputs.application }}
        config: |
          
          # Change these to match the environment mapping for your environment!
          
          preview:
            cluster: https://github.com/YOUR_ORG/argocd-deploy-non-prod/blob/main/plat/use1-dev/apps
            cluster-role: arn:aws:iam::DEV_ACCOUNT_ID:role/acme-plat-use1-dev-eks-gha
            namespace: ${{ inputs.namespace }}
            ssm-path: platform/acme-plat-use1-dev-eks-cluster
            reformat: branch-name

          dev:
            cluster: https://github.com/YOUR_ORG/argocd-deploy-non-prod/blob/main/plat/use1-dev/apps
            cluster-role: arn:aws:iam::DEV_ACCOUNT_ID:role/acme-plat-use1-dev-eks-gha
            namespace: dev
            ssm-path: platform/acme-plat-use1-dev-eks-cluster

          staging:
            cluster: https://github.com/YOUR_ORG/argocd-deploy-prod/blob/main/plat/use1-staging/apps
            cluster-role: arn:aws:iam::STAGING_ACCOUNT_ID:role/acme-plat-use1-staging-eks-gha
            namespace: staging
            ssm-path: platform/acme-plat-use1-staging-eks-cluster
                      
          prod:
            cluster: https://github.com/YOUR_ORG/argocd-deploy-prod/blob/main/plat/use1-prod/apps
            cluster-role: arn:aws:iam::PROD_ACCOUNT_ID:role/acme-plat-use1-prod-eks-gha
            namespace: prod
            ssm-path: platform/acme-plat-use1-prod-eks-cluster

```

**Reply by dukarc** [reply]
Thanks @milldr .. i'm not seeing where this is referenced .. is it used by other actions?

**Reply by milldr** [reply]
It's used as part of the release engineering workflows for app repos to deploy or destroy apps on EKS cluster with Argo CD. For example:
https://github.com/cloudposse-examples/app-on-eks-with-argocd/blob/master/.github/workflows/workflow-cd-preview-argocd.yml#L167-L178

More on these application repositories here:
https://docs.cloudposse.com/layers/software-delivery/eks-argocd/#deployment

**Reply by milldr** [reply]
Also, please review this section for more requirements for setting up application repository release engineering:
https://docs.cloudposse.com/layers/software-delivery/eks-argocd/setup/#next-steps

**Reply by dukarc** [reply]
Thanks,

1. Any recommendations on a good way to test if we have this working?  Could i just create a dummy branch in the same repo and attempt to echo the outputs of this?

```
      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.3.0
        id: environment
        with:
          implementation_repository: 'cloudposse-examples/infra-config'
          implementation_path: '.github/environments/'
          implementation_file: 'eks-argocd.yml'
          implementation_ref: 'main'
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: ${{ matrix.env }}
          namespace: ${{ needs.preview.outputs.namespace }}
          repository: ${{ inputs.repository }}
```

2. Could use some clarification on what to use for these entries?
```
ssm-path: platform/vbpt-plat-usw2-dev-eks-cluster
reformat: branch-name
```
