### DISCUSSION TITLE
Re-enable ECR?

### DISCUSSION THREAD

**Discussion by dukarc** [cloudposse/community#76] [Essential Support] [answered]
Hi Folks,

In our refarch kickoff we had commented out this code for ECR so we could progress with other setup steps... now that we are beyond these should we now enable it?

```
components:
  terraform:
    ecr:
      vars:
        enabled: true
        ecr_user_enabled: false
        enable_lifecycle_policy: true
        protected_tags: []
        image_tag_mutability: MUTABLE
        max_image_count: 500
        scan_images_on_push: true
        # github_actions_iam_role_enabled: false
        # github_actions_iam_role_attributes: [ "ecr" ]
        # github_actions_allowed_repos:
        #   - Vibrant-Planet/vbpt-infra
        #   - Vibrant-Planet/example-app-on-ecs
        #   - Vibrant-Planet/example-app-on-lambda-with-gha
        read_only_account_role_map:
          plat-dev: ["*"]
          plat-sandbox: ["*"]
          plat-staging: ["*"]
          plat-prod: ["*"]
        read_write_account_role_map:
          core-identity:
            - devops
            - developers
          core-auto:
            - admin
            - poweruser
        # ECR must be all lowercase
        images:
          - vibrant-planet/vbpt-infra
          - vibrant-planet/example-app-on-ecs
          - vibrant-planet/example-app-on-lambda-with-gha
```
